apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: secrets
deploy:
  kubectl:
    manifests:
      - ../.kubernetes/redis/secrets.yaml
      - ../.kubernetes/rabbitmq/secrets.yaml
      - ../.kubernetes/converso/secrets.yaml
      - ../.kubernetes/converso_telegram_bot/secrets.yaml