
apiVersion: v1
kind: Service
metadata:
  name: converso-service
  namespace: converso
spec:
  selector:
    app: converso
  ports:
    - name: rest
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: debug
      protocol: TCP
      port: 5678
      targetPort: 5678