apiVersion: apps/v1
kind: Deployment
metadata:
  name: converso-telegram-bot
  namespace: converso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converso-telegram-bot
  template:
    metadata:
      labels:
        app: converso-telegram-bot
    spec:
      containers:
        - name: converso-telegram-bot
          image: converso-telegram-bot
          imagePullPolicy: Never
          env:
            - name: converso_URL
              value: converso-service:8000
            - name: TELEGRAM_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: converso-telegram-bot-secret
                  key: TELEGRAM_API_TOKEN
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: converso-secret
                  key: OPENAI_API_KEY
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: converso-secret
                  key: REDIS_PASSWORD
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-custom-secret
                  key: rabbitmq-password
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"