apiVersion: v1
kind: Service
metadata:
  name: converso-telegram-bot-service
  namespace: converso
spec:
  selector:
    app: converso-telegram-bot
  ports:
    - name: debug
      protocol: TCP
      port: 5679
      targetPort: 5678