name: Linter

on:
  push:
    branches: 
    - "main"
  pull_request:
    branches: 
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies [converso]
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        cd converso
        poetry install --with lint
    - name: Analysing the code with pylint
      run: |
        cd converso
        poetry run python -m pylint $(git ls-files '*.py') --rcfile=../pylint.rc --fail-under=8
    - name: Installing dependencies [converso-telegram-bot]
      run: |
        cd converso_telegram_bot
        poetry install --with lint
    - name: Analysing the code with pylint [converso-telegram-bot]
      run: |
        cd converso_telegram_bot
        poetry run python -m pylint $(git ls-files '*.py') --rcfile=../pylint.rc --fail-under=8